"""Phase 1A spike: producer mTLS transport / certificate-exposure evidence.

See docs/spikes/producer-mtls-certificate-exposure.md for the full write-up
this test suite feeds. This module is the technical evidence backing that
document's Outcome A/B decision — it is not throwaway experimentation and
should be retained across Phase 1B.

Two independent proofs are gathered here:

1. ``TestRawAsyncioSslPeerCertificateVisibility`` — a real TLS connection
   using nothing but the Python standard library (``asyncio`` + ``ssl``),
   completely bypassing Uvicorn/ASGI. This establishes the ground truth:
   the validated peer certificate — including URI SAN values — *is*
   available at the TLS/transport layer once a client certificate is
   required and validated. Nothing above this layer is required to make
   the certificate exist; the question this spike actually resolves is
   whether *Uvicorn plumbs it up to the ASGI application*.

2. ``TestUvicornGatewayStackAsgiScopeExposure`` — the real subject under
   test: an actual Uvicorn HTTP server, configured exactly the way
   basis-gateway would configure it (``ssl_certfile``/``ssl_keyfile``/
   ``ssl_ca_certs``/``ssl_cert_reqs``), fronting a minimal ASGI application
   (``tests/integration/spike_app.py``). Every scenario in
   Step 4/5/6/7/8 of the Phase 1A brief is exercised here: trusted client,
   untrusted-CA client, missing client certificate, expired client
   certificate, zero/one/multiple URI SAN shapes, and HTTP header
   spoofability.

No mocked certificate objects are used anywhere in this module — every
scenario is a real TCP/TLS handshake against a real bound socket on
``127.0.0.1``, using a fresh test-only CA generated by
``tests/integration/mtls_certs.py``.
"""

from __future__ import annotations

import asyncio
import socket
import ssl
import subprocess
import sys
import time
from collections.abc import Iterator
from pathlib import Path

import httpx
import pytest
from mtls_certs import (
    MULTI_URI_SAN_A,
    MULTI_URI_SAN_B,
    ONE_URI_SAN,
    MTLSFixtureSet,
    build_fixture_set,
)

pytestmark = pytest.mark.integration

_SPIKE_APP_DIR = Path(__file__).parent
_STARTUP_TIMEOUT_SECONDS = 10.0


def _free_port() -> int:
    """Reserve an ephemeral TCP port on 127.0.0.1 for the spike server.

    There is an inherent (very small) TOCTOU race between closing this
    socket and Uvicorn binding the same port; this is the standard,
    widely-used approach for test-only ephemeral ports and has not been a
    source of flakiness in this repository's other integration tests.
    """
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.bind(("127.0.0.1", 0))
        return s.getsockname()[1]


class MTLSSpikeServer:
    """Launches ``spike_app:app`` under a real Uvicorn subprocess, TLS-only,
    client-certificate-required, trusting only the spike's test CA."""

    def __init__(self, fixtures: MTLSFixtureSet, port: int) -> None:
        self._fixtures = fixtures
        self.port = port
        self._process: subprocess.Popen[bytes] | None = None

    def start(self) -> None:
        cmd = [
            sys.executable,
            "-m",
            "uvicorn",
            "spike_app:app",
            "--host",
            "127.0.0.1",
            "--port",
            str(self.port),
            "--ssl-certfile",
            str(self._fixtures.server.cert_path),
            "--ssl-keyfile",
            str(self._fixtures.server.key_path),
            "--ssl-ca-certs",
            str(self._fixtures.ca.cert_path),
            # ssl.CERT_REQUIRED == 2. Uvicorn's CLI takes the raw ssl.VerifyMode
            # integer value for --ssl-cert-reqs.
            "--ssl-cert-reqs",
            str(int(ssl.CERT_REQUIRED)),
            "--log-level",
            "warning",
        ]
        self._process = subprocess.Popen(  # noqa: S603
            cmd,
            cwd=str(_SPIKE_APP_DIR),
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
        )
        self._wait_until_accepting_tls()

    def _wait_until_accepting_tls(self) -> None:
        """Block until the server is accepting TCP connections on self.port.

        Does not attempt a full TLS handshake here (that would require a
        trusted client certificate this helper doesn't know about) — a bare
        TCP connect is sufficient to know Uvicorn has bound the port and is
        listening, which is all that is needed before the real test
        scenarios below drive their own TLS handshakes.
        """
        deadline = time.monotonic() + _STARTUP_TIMEOUT_SECONDS
        last_error: Exception | None = None
        while time.monotonic() < deadline:
            assert self._process is not None
            if self._process.poll() is not None:
                output = self._process.stdout.read().decode() if self._process.stdout else ""
                raise RuntimeError(
                    f"spike Uvicorn server exited early (code={self._process.returncode}): {output}"
                )
            try:
                with socket.create_connection(("127.0.0.1", self.port), timeout=0.5):
                    return
            except OSError as exc:  # noqa: PERF203
                last_error = exc
                time.sleep(0.1)
        raise RuntimeError(f"spike Uvicorn server did not start in time: {last_error}")

    def stop(self) -> None:
        if self._process is None:
            return
        self._process.terminate()
        try:
            self._process.wait(timeout=5)
        except subprocess.TimeoutExpired:
            self._process.kill()
            self._process.wait(timeout=5)


@pytest.fixture(scope="module")
def mtls_fixtures(tmp_path_factory: pytest.TempPathFactory) -> MTLSFixtureSet:
    return build_fixture_set(tmp_path_factory.mktemp("producer-mtls-spike-pki"))


@pytest.fixture(scope="module")
def spike_server(mtls_fixtures: MTLSFixtureSet) -> Iterator[MTLSSpikeServer]:
    server = MTLSSpikeServer(mtls_fixtures, _free_port())
    server.start()
    try:
        yield server
    finally:
        server.stop()


def _client(mtls_fixtures: MTLSFixtureSet, client_cert: str | None) -> httpx.Client:
    """Build an httpx client trusting the spike CA, optionally presenting a
    client certificate. ``client_cert`` names an ``MTLSFixtureSet`` attribute
    prefix, e.g. ``"client_one_uri_san"``.

    Builds an explicit ``ssl.SSLContext`` rather than passing httpx's
    ``verify=<path str>``/``cert=<tuple>`` kwargs directly: in the installed
    httpx version, ``create_ssl_context()`` returns early for a string
    ``verify`` value (after emitting a deprecation warning) *before* it
    reaches the code that applies ``cert`` via ``load_cert_chain`` — so the
    client certificate is silently never presented. Constructing the context
    ourselves and calling ``load_cert_chain`` on it directly sidesteps that
    entirely and is unaffected by that ordering bug.
    """
    context = ssl.create_default_context(cafile=str(mtls_fixtures.ca.cert_path))
    if client_cert is not None:
        generated = getattr(mtls_fixtures, client_cert)
        context.load_cert_chain(certfile=str(generated.cert_path), keyfile=str(generated.key_path))
    return httpx.Client(
        verify=context,
        # This spike talks only to 127.0.0.1; disabling trust_env avoids the
        # client picking up an ambient HTTP(S)_PROXY/ALL_PROXY from the
        # environment and routing the mTLS handshake through it.
        trust_env=False,
    )


class TestRawAsyncioSslPeerCertificateVisibility:
    """Ground truth: the TLS/transport layer *does* expose the validated
    peer certificate, independent of any ASGI server. This isolates
    "is the data obtainable via TLS at all" from "does Uvicorn plumb it
    into the ASGI application" (the second question is what Outcome A/B
    actually turns on)."""

    def test_trusted_client_uri_san_visible_via_raw_ssl_object(
        self, mtls_fixtures: MTLSFixtureSet
    ) -> None:
        peercert = asyncio.run(
            self._handshake_and_get_peercert(mtls_fixtures, mtls_fixtures.client_one_uri_san)
        )
        assert peercert is not None
        san = peercert.get("subjectAltName", ())
        uri_sans = [value for kind, value in san if kind == "URI"]
        assert uri_sans == [ONE_URI_SAN]

    def test_zero_uri_san_client_connects_and_is_distinguishable_at_raw_ssl_layer(
        self, mtls_fixtures: MTLSFixtureSet
    ) -> None:
        peercert = asyncio.run(
            self._handshake_and_get_peercert(mtls_fixtures, mtls_fixtures.client_zero_uri_san)
        )
        assert peercert is not None
        san = peercert.get("subjectAltName", ())
        uri_sans = [value for kind, value in san if kind == "URI"]
        assert uri_sans == []

    def test_multi_uri_san_client_connects_and_is_distinguishable_at_raw_ssl_layer(
        self, mtls_fixtures: MTLSFixtureSet
    ) -> None:
        peercert = asyncio.run(
            self._handshake_and_get_peercert(mtls_fixtures, mtls_fixtures.client_multi_uri_san)
        )
        assert peercert is not None
        san = peercert.get("subjectAltName", ())
        uri_sans = [value for kind, value in san if kind == "URI"]
        assert sorted(uri_sans) == sorted([MULTI_URI_SAN_A, MULTI_URI_SAN_B])

    @staticmethod
    async def _handshake_and_get_peercert(fixtures: MTLSFixtureSet, client_cert) -> dict | None:  # type: ignore[no-untyped-def]
        server_ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
        server_ctx.load_cert_chain(
            certfile=str(fixtures.server.cert_path), keyfile=str(fixtures.server.key_path)
        )
        server_ctx.verify_mode = ssl.CERT_REQUIRED
        server_ctx.load_verify_locations(cafile=str(fixtures.ca.cert_path))

        observed: dict[str, object] = {}

        async def handle(reader: asyncio.StreamReader, writer: asyncio.StreamWriter) -> None:
            ssl_object = writer.get_extra_info("ssl_object")
            observed["peercert"] = ssl_object.getpeercert() if ssl_object else None
            writer.close()
            await writer.wait_closed()

        server = await asyncio.start_server(handle, "127.0.0.1", 0, ssl=server_ctx)
        try:
            port = server.sockets[0].getsockname()[1]  # type: ignore[union-attr,index]
            client_ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_CLIENT)
            client_ctx.load_verify_locations(cafile=str(fixtures.ca.cert_path))
            client_ctx.load_cert_chain(
                certfile=str(client_cert.cert_path), keyfile=str(client_cert.key_path)
            )
            _reader, writer = await asyncio.open_connection(
                "127.0.0.1", port, ssl=client_ctx, server_hostname="127.0.0.1"
            )
            writer.close()
            await writer.wait_closed()
        finally:
            server.close()
            await server.wait_closed()

        return observed.get("peercert")  # type: ignore[return-value]


class TestUvicornGatewayStackAsgiScopeExposure:
    """The actual subject of Phase 1A: run a real Uvicorn server, configured
    the way basis-gateway would configure it, and determine what the ASGI
    application layer can and cannot observe."""

    # ── Layer 1: TLS transport authentication ──────────────────────────

    def test_trusted_client_certificate_handshake_succeeds_and_handler_runs(
        self, mtls_fixtures: MTLSFixtureSet, spike_server: MTLSSpikeServer
    ) -> None:
        with _client(mtls_fixtures, "client_one_uri_san") as client:
            response = client.get(f"https://127.0.0.1:{spike_server.port}/introspect")
        assert response.status_code == 200

    def test_untrusted_ca_client_certificate_fails_before_http_handler_runs(
        self, mtls_fixtures: MTLSFixtureSet, spike_server: MTLSSpikeServer
    ) -> None:
        with (
            pytest.raises(httpx.TransportError),
            _client(mtls_fixtures, "client_untrusted_ca") as client,
        ):
            client.get(f"https://127.0.0.1:{spike_server.port}/introspect")

    def test_missing_client_certificate_fails_before_http_handler_runs(
        self, mtls_fixtures: MTLSFixtureSet, spike_server: MTLSSpikeServer
    ) -> None:
        with pytest.raises(httpx.TransportError), _client(mtls_fixtures, None) as client:
            client.get(f"https://127.0.0.1:{spike_server.port}/introspect")

    def test_expired_client_certificate_fails_before_http_handler_runs(
        self, mtls_fixtures: MTLSFixtureSet, spike_server: MTLSSpikeServer
    ) -> None:
        with (
            pytest.raises(httpx.TransportError),
            _client(mtls_fixtures, "client_expired") as client,
        ):
            client.get(f"https://127.0.0.1:{spike_server.port}/introspect")

    # ── Layer 2 input boundary: what can the ASGI application observe? ──

    def test_asgi_scope_has_no_extensions_key_for_trusted_mtls_connection(
        self, mtls_fixtures: MTLSFixtureSet, spike_server: MTLSSpikeServer
    ) -> None:
        """The central negative finding: even for a successfully validated,
        trusted client certificate, stock Uvicorn provides no ``extensions``
        scope entry at all — let alone the ASGI ``tls`` extension
        (https://asgi.readthedocs.io/en/latest/specs/tls.html) that would
        carry ``client_cert_chain``/``client_cert_name``. The application
        cannot distinguish "connected over validated mTLS" from "connected
        over plain HTTPS with no client certificate" other than by
        ``scheme == "https"``."""
        with _client(mtls_fixtures, "client_one_uri_san") as client:
            response = client.get(f"https://127.0.0.1:{spike_server.port}/introspect")
        body = response.json()
        assert body["scheme"] == "https"
        assert body["has_extensions_key"] is False
        assert body["extension_names"] == []
        assert body["tls_extension"] is None
        assert "extensions" not in body["scope_keys"]

    def test_asgi_scope_keys_are_exactly_the_documented_uvicorn_set(
        self, mtls_fixtures: MTLSFixtureSet, spike_server: MTLSSpikeServer
    ) -> None:
        with _client(mtls_fixtures, "client_one_uri_san") as client:
            response = client.get(f"https://127.0.0.1:{spike_server.port}/introspect")
        body = response.json()
        assert body["scope_keys"] == sorted(
            [
                "asgi",
                "client",
                "headers",
                "http_version",
                "method",
                "path",
                "query_string",
                "raw_path",
                "root_path",
                "scheme",
                "server",
                "state",
                "type",
            ]
        )

    def test_zero_and_multi_uri_san_certificates_are_indistinguishable_at_application_layer(
        self, mtls_fixtures: MTLSFixtureSet, spike_server: MTLSSpikeServer
    ) -> None:
        """TLS accepts all three URI-SAN shapes (Step 6 of the Phase 1A
        brief); this test proves the ASGI application response is *identical*
        regardless of which shape connected — the zero/one/multiple
        distinction Phase 1B needs is invisible above the TLS layer under
        stock Uvicorn."""
        bodies = {}
        for name in ("client_zero_uri_san", "client_one_uri_san", "client_multi_uri_san"):
            with _client(mtls_fixtures, name) as client:
                response = client.get(f"https://127.0.0.1:{spike_server.port}/introspect")
            assert response.status_code == 200
            bodies[name] = response.json()
        # Every response has the identical shape: no cert data anywhere.
        for body in bodies.values():
            assert body["has_extensions_key"] is False
            assert body["tls_extension"] is None

    # ── Step 7: header-spoofing analysis ────────────────────────────────

    @pytest.mark.parametrize(
        "header_name",
        [
            "X-Client-Cert",
            "X-SSL-Client-Cert",
            "X-Client-DN",
            "X-Forwarded-Client-Cert",
        ],
    )
    def test_ordinary_caller_can_freely_set_certificate_looking_headers(
        self,
        mtls_fixtures: MTLSFixtureSet,
        spike_server: MTLSSpikeServer,
        header_name: str,
    ) -> None:
        """Proves these headers are NOT an acceptable producer-identity
        boundary for direct termination: an ordinary, already-trusted mTLS
        caller can set an arbitrary value in a certificate-looking header
        and the ASGI application receives it completely unmodified — nothing
        in this stack strips, overwrites, or otherwise protects it."""
        spoofed_value = "URI:spiffe://example.test/basis/attacker-supplied-identity"
        with _client(mtls_fixtures, "client_one_uri_san") as client:
            response = client.get(
                f"https://127.0.0.1:{spike_server.port}/introspect",
                headers={header_name: spoofed_value},
            )
        body = response.json()
        assert body["headers"][header_name.lower()] == spoofed_value
